Fixing small bug
biopet/findoverlapmatch pull request #4
Opened 2017-11-07 14:55 UTC by ffinfo

### Description

----

### Checklist (never delete this)

- [ ] Each method/class/object/trait should have scaladocs
- [ ] Added methods are unit tested
- [ ] Test coverage may not drop
- [ ] Documentation should be updated if required

2017-11-07 16:06 UTC, rhpvorderman approved these changes

2017-11-07 16:06 UTC, rhpvorderman requested changes
Can you test this change?

2017-11-08 08:42 UTC, ffinfo commented
Was not aware this was not automatically covered already. Seems that this test is less tested then I hoped. Will look into this

2017-11-08 11:42 UTC, ffinfo commented
@rhpvorderman: Can you check again? I now added some testing, also parts that had nothing todo with this PR ;)

2017-11-09 13:55 UTC, rhpvorderman approved these changes

2017-11-09 13:55 UTC, merged